services:
  db:
    image: postgres:15
    container_name: database-plss
    restart: always
    environment:
      POSTGRES_DB: database-plss
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - laravel

networks:
  laravel:

volumes:
  pgdata:
